# Generated by Django 5.0.3 on 2024-03-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Gym',
        ),
    ]
