# Generated by Django 5.0.3 on 2024-03-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_tracker', '0009_alter_workout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Сидячий образ жизни'), ('moderate', 'Умеренная активность'), ('high', 'Высокая активность')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='', max_length=1),
        ),
    ]
