# Generated by Django 5.0.3 on 2024-03-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_tracker', '0015_alter_userprofile_height_alter_userprofile_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(default=22),
            preserve_default=False,
        ),
    ]
